package:
  name: pyastrometry
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_rev:
  git_url: git@waxwing:/opt/git/Astronomy/Python/Utilities/pyastrometry.git

requirements:
  host:
   - python
   - setuptools
  run:
   - python==3.6
   - numpy >=1.15
   - astropy >=3.0.4
   - configobj >=5.0.6
   - pyqt >=5.9.2
   - pyastroimageview >=0.8

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ 'py' + environ.get('CONDA_PY') + environ.get('GIT_DESCRIBE_HASH', '') + '_' + environ.get('GIT_DESCRIBE_NUMBER', '0')}}

about:
  home:
  license:
  license_file:
