# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyastrometry_qt_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(274, 313)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.pixelscale_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pixelscale_spinbox.setObjectName("pixelscale_spinbox")
        self.gridLayout_3.addWidget(self.pixelscale_spinbox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 4, 1, 1)
        self.platesolve2_num_regions_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.platesolve2_num_regions_spinbox.setObjectName("platesolve2_num_regions_spinbox")
        self.gridLayout.addWidget(self.platesolve2_num_regions_spinbox, 2, 2, 1, 2)
        self.platesolve2_waittime_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.platesolve2_waittime_spinbox.setObjectName("platesolve2_waittime_spinbox")
        self.gridLayout.addWidget(self.platesolve2_waittime_spinbox, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.setup_platesolve2_loc_button = QtWidgets.QPushButton(self.groupBox)
        self.setup_platesolve2_loc_button.setObjectName("setup_platesolve2_loc_button")
        self.gridLayout.addWidget(self.setup_platesolve2_loc_button, 1, 4, 1, 1)
        self.platesolve2_exec_path_lbl = QtWidgets.QLabel(self.groupBox)
        self.platesolve2_exec_path_lbl.setText("")
        self.platesolve2_exec_path_lbl.setObjectName("platesolve2_exec_path_lbl")
        self.gridLayout.addWidget(self.platesolve2_exec_path_lbl, 0, 1, 1, 3)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.astrometry_timeout_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.astrometry_timeout_spinbox.setObjectName("astrometry_timeout_spinbox")
        self.gridLayout_2.addWidget(self.astrometry_timeout_spinbox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "General"))
        self.label_8.setText(_translate("Dialog", "Pixel Scale"))
        self.label_9.setText(_translate("Dialog", "arc-seconds/pixel"))
        self.groupBox.setTitle(_translate("Dialog", "PlateSolve2"))
        self.label_3.setText(_translate("Dialog", "Regions to search"))
        self.label_5.setText(_translate("Dialog", "seconds"))
        self.label.setText(_translate("Dialog", "Program Location"))
        self.label_4.setText(_translate("Dialog", "Wait time"))
        self.setup_platesolve2_loc_button.setText(_translate("Dialog", "Setup"))
        self.groupBox_2.setTitle(_translate("Dialog", "Astrometry.net"))
        self.label_6.setText(_translate("Dialog", "Timeout"))
        self.label_7.setText(_translate("Dialog", "seconds"))

