# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyastrometry_qt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(329, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.telescope_driver_label = QtWidgets.QLabel(self.groupBox_3)
        self.telescope_driver_label.setObjectName("telescope_driver_label")
        self.gridLayout_3.addWidget(self.telescope_driver_label, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cur_ra_j2000_label = QtWidgets.QLabel(self.groupBox)
        self.cur_ra_j2000_label.setObjectName("cur_ra_j2000_label")
        self.gridLayout.addWidget(self.cur_ra_j2000_label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cur_dec_j2000_label = QtWidgets.QLabel(self.groupBox)
        self.cur_dec_j2000_label.setObjectName("cur_dec_j2000_label")
        self.gridLayout.addWidget(self.cur_dec_j2000_label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.cur_ra_jnow_label = QtWidgets.QLabel(self.groupBox)
        self.cur_ra_jnow_label.setObjectName("cur_ra_jnow_label")
        self.gridLayout.addWidget(self.cur_ra_jnow_label, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.cur_dec_jnow_label = QtWidgets.QLabel(self.groupBox)
        self.cur_dec_jnow_label.setObjectName("cur_dec_jnow_label")
        self.gridLayout.addWidget(self.cur_dec_jnow_label, 3, 1, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.groupBox)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.gridLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.solve_ra_jnow_label = QtWidgets.QLabel(self.groupBox_2)
        self.solve_ra_jnow_label.setObjectName("solve_ra_jnow_label")
        self.gridLayout_2.addWidget(self.solve_ra_jnow_label, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.solve_ra_j2000_label = QtWidgets.QLabel(self.groupBox_2)
        self.solve_ra_j2000_label.setObjectName("solve_ra_j2000_label")
        self.gridLayout_2.addWidget(self.solve_ra_j2000_label, 0, 1, 1, 1)
        self.solve_dec_jnow_label = QtWidgets.QLabel(self.groupBox_2)
        self.solve_dec_jnow_label.setObjectName("solve_dec_jnow_label")
        self.gridLayout_2.addWidget(self.solve_dec_jnow_label, 3, 1, 1, 1)
        self.solve_dec_j2000_label = QtWidgets.QLabel(self.groupBox_2)
        self.solve_dec_j2000_label.setObjectName("solve_dec_j2000_label")
        self.gridLayout_2.addWidget(self.solve_dec_j2000_label, 1, 1, 1, 1)
        self.solve_image_button = QtWidgets.QPushButton(self.groupBox_2)
        self.solve_image_button.setObjectName("solve_image_button")
        self.gridLayout_2.addWidget(self.solve_image_button, 6, 0, 1, 1)
        self.solve_file_button = QtWidgets.QPushButton(self.groupBox_2)
        self.solve_file_button.setObjectName("solve_file_button")
        self.gridLayout_2.addWidget(self.solve_file_button, 5, 0, 1, 1)
        self.sync_pos_button = QtWidgets.QPushButton(self.groupBox_2)
        self.sync_pos_button.setObjectName("sync_pos_button")
        self.gridLayout_2.addWidget(self.sync_pos_button, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 2)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 329, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Telescope"))
        self.telescope_driver_label.setText(_translate("MainWindow", "Simulator"))
        self.label.setText(_translate("MainWindow", "Telescope Driver"))
        self.groupBox.setTitle(_translate("MainWindow", "Current Position"))
        self.label_2.setText(_translate("MainWindow", "Current RA (J2000)"))
        self.cur_ra_j2000_label.setText(_translate("MainWindow", "--:--:--"))
        self.label_3.setText(_translate("MainWindow", "Current DEC (J2000)"))
        self.cur_dec_j2000_label.setText(_translate("MainWindow", "--:--:--"))
        self.label_5.setText(_translate("MainWindow", "Current RA (JNow)"))
        self.cur_ra_jnow_label.setText(_translate("MainWindow", "--:--:--"))
        self.label_4.setText(_translate("MainWindow", "Current DEC (JNow)"))
        self.cur_dec_jnow_label.setText(_translate("MainWindow", "--:--:--"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Plate Solve"))
        self.label_7.setText(_translate("MainWindow", "Solved DEC (J2000)"))
        self.label_6.setText(_translate("MainWindow", "Solved DEC (JNow)"))
        self.label_8.setText(_translate("MainWindow", "Solved  RA (J2000)"))
        self.solve_ra_jnow_label.setText(_translate("MainWindow", "--:--:--"))
        self.label_9.setText(_translate("MainWindow", "Solved RA (JNow)"))
        self.solve_ra_j2000_label.setText(_translate("MainWindow", "--:--:--"))
        self.solve_dec_jnow_label.setText(_translate("MainWindow", "--:--:--"))
        self.solve_dec_j2000_label.setText(_translate("MainWindow", "--:--:--"))
        self.solve_image_button.setText(_translate("MainWindow", "Solve Image"))
        self.solve_file_button.setText(_translate("MainWindow", "Solve File"))
        self.sync_pos_button.setText(_translate("MainWindow", "Sync"))

