# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyastrometry_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 636)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.pixelscale_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pixelscale_spinbox.setObjectName("pixelscale_spinbox")
        self.gridLayout_3.addWidget(self.pixelscale_spinbox, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 2, 1, 1)
        self.plate_solve_camera_exposure_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.plate_solve_camera_exposure_spinbox.setObjectName("plate_solve_camera_exposure_spinbox")
        self.gridLayout_3.addWidget(self.plate_solve_camera_exposure_spinbox, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.plate_solve_camera_binning_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.plate_solve_camera_binning_spinbox.setMinimum(1)
        self.plate_solve_camera_binning_spinbox.setMaximum(4)
        self.plate_solve_camera_binning_spinbox.setObjectName("plate_solve_camera_binning_spinbox")
        self.gridLayout_3.addWidget(self.plate_solve_camera_binning_spinbox, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.plate_solve_precise_slew_limit_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.plate_solve_precise_slew_limit_spinbox.setMaximum(900.0)
        self.plate_solve_precise_slew_limit_spinbox.setObjectName("plate_solve_precise_slew_limit_spinbox")
        self.gridLayout_3.addWidget(self.plate_solve_precise_slew_limit_spinbox, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 1, 1, 2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.platesolve2_groupbox = QtWidgets.QGroupBox(Dialog)
        self.platesolve2_groupbox.setObjectName("platesolve2_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.platesolve2_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.platesolve2_groupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.platesolve2_groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 4, 1, 1)
        self.platesolve2_num_regions_spinbox = QtWidgets.QSpinBox(self.platesolve2_groupbox)
        self.platesolve2_num_regions_spinbox.setMaximum(999)
        self.platesolve2_num_regions_spinbox.setObjectName("platesolve2_num_regions_spinbox")
        self.gridLayout.addWidget(self.platesolve2_num_regions_spinbox, 2, 2, 1, 2)
        self.platesolve2_waittime_spinbox = QtWidgets.QSpinBox(self.platesolve2_groupbox)
        self.platesolve2_waittime_spinbox.setObjectName("platesolve2_waittime_spinbox")
        self.gridLayout.addWidget(self.platesolve2_waittime_spinbox, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.platesolve2_groupbox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.platesolve2_groupbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.setup_platesolve2_loc_button = QtWidgets.QPushButton(self.platesolve2_groupbox)
        self.setup_platesolve2_loc_button.setObjectName("setup_platesolve2_loc_button")
        self.gridLayout.addWidget(self.setup_platesolve2_loc_button, 1, 4, 1, 1)
        self.platesolve2_exec_path_lbl = QtWidgets.QLabel(self.platesolve2_groupbox)
        self.platesolve2_exec_path_lbl.setText("")
        self.platesolve2_exec_path_lbl.setObjectName("platesolve2_exec_path_lbl")
        self.gridLayout.addWidget(self.platesolve2_exec_path_lbl, 0, 1, 1, 3)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.platesolve2_groupbox)
        self.astrometrynetlocal_groupbox = QtWidgets.QGroupBox(Dialog)
        self.astrometrynetlocal_groupbox.setObjectName("astrometrynetlocal_groupbox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.astrometrynetlocal_groupbox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.astrometrynetlocal_exec_path_lbl = QtWidgets.QLabel(self.astrometrynetlocal_groupbox)
        self.astrometrynetlocal_exec_path_lbl.setText("")
        self.astrometrynetlocal_exec_path_lbl.setObjectName("astrometrynetlocal_exec_path_lbl")
        self.gridLayout_4.addWidget(self.astrometrynetlocal_exec_path_lbl, 0, 1, 1, 2)
        self.setup_astrometrynetlocal_loc_button = QtWidgets.QPushButton(self.astrometrynetlocal_groupbox)
        self.setup_astrometrynetlocal_loc_button.setObjectName("setup_astrometrynetlocal_loc_button")
        self.gridLayout_4.addWidget(self.setup_astrometrynetlocal_loc_button, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.astrometrynetlocal_groupbox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.astrometrynetlocal_groupbox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.setup_astrometrynetlocal_search_rad_deg = QtWidgets.QSpinBox(self.astrometrynetlocal_groupbox)
        self.setup_astrometrynetlocal_search_rad_deg.setMaximum(25)
        self.setup_astrometrynetlocal_search_rad_deg.setObjectName("setup_astrometrynetlocal_search_rad_deg")
        self.gridLayout_4.addWidget(self.setup_astrometrynetlocal_search_rad_deg, 2, 1, 1, 1)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.astrometrynetlocal_groupbox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.astrometry_apikey = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.astrometry_apikey.setMinimumSize(QtCore.QSize(0, 24))
        self.astrometry_apikey.setMaximumSize(QtCore.QSize(16777215, 24))
        self.astrometry_apikey.setObjectName("astrometry_apikey")
        self.gridLayout_2.addWidget(self.astrometry_apikey, 2, 1, 1, 2)
        self.astrometry_downsample_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.astrometry_downsample_spinbox.setMinimum(1)
        self.astrometry_downsample_spinbox.setMaximum(4)
        self.astrometry_downsample_spinbox.setObjectName("astrometry_downsample_spinbox")
        self.gridLayout_2.addWidget(self.astrometry_downsample_spinbox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.astrometry_timeout_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.astrometry_timeout_spinbox.setMaximum(999)
        self.astrometry_timeout_spinbox.setObjectName("astrometry_timeout_spinbox")
        self.gridLayout_2.addWidget(self.astrometry_timeout_spinbox, 0, 1, 1, 1)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "General"))
        self.label_11.setText(_translate("Dialog", "Camera Binning"))
        self.label_10.setText(_translate("Dialog", "seconds"))
        self.label_8.setText(_translate("Dialog", "Pixel Scale (bin x 1)"))
        self.label_14.setText(_translate("Dialog", "arc-seconds"))
        self.label_13.setText(_translate("Dialog", "Precise Slew Limit"))
        self.label_9.setText(_translate("Dialog", "arc-seconds/pixel"))
        self.label_2.setText(_translate("Dialog", "Camera Exposure"))
        self.label_16.setText(_translate("Dialog", "(Enter 0 to force guess)"))
        self.platesolve2_groupbox.setTitle(_translate("Dialog", "PlateSolve2"))
        self.label_3.setText(_translate("Dialog", "Regions to search"))
        self.label_5.setText(_translate("Dialog", "seconds"))
        self.label.setText(_translate("Dialog", "Program Location"))
        self.label_4.setText(_translate("Dialog", "Wait time"))
        self.setup_platesolve2_loc_button.setText(_translate("Dialog", "Setup"))
        self.astrometrynetlocal_groupbox.setTitle(_translate("Dialog", "Local Astrometry.net"))
        self.setup_astrometrynetlocal_loc_button.setText(_translate("Dialog", "Setup"))
        self.label_18.setText(_translate("Dialog", "Program Location"))
        self.label_17.setText(_translate("Dialog", "Search Radius"))
        self.setup_astrometrynetlocal_search_rad_deg.setSuffix(_translate("Dialog", " degrees"))
        self.groupBox_2.setTitle(_translate("Dialog", "Astrometry.net"))
        self.label_15.setText(_translate("Dialog", "API Key"))
        self.label_12.setText(_translate("Dialog", "Downsample"))
        self.label_7.setText(_translate("Dialog", "seconds"))
        self.label_6.setText(_translate("Dialog", "Timeout"))

